### ISSUE TITLE
bhkata listában közösségi szerep jelölés - misszionárius

### ISSUE THREAD

**Issue by rrd108** [rrd108/bhaktanyilvantartas#11]

**Comment by ifjuszalaimihaly** [comment]
Csak a misszionáriust kell betenni egy plussz oszlopba, ha az rendelhető hozzá a communityroles-ben?

**Comment by rrd108** [comment]
Ez a departments/members listáról szól, ahol a misszionáriusok pipával jelöve vannak már. Az issue az, hogy nyomtatáskor nem látszanak a pipák.

**Comment by ifjuszalaimihaly** [comment]
Végignéztem több oldalnak a nyomatatási képét. Úgy látom, hogy azok nem jelennek meg, ahol edit, add, vagy delete típusú link van.
