### ISSUE TITLE
change to supporter

### ISSUE THREAD

**Issue by rrd108** [rrd108/bhaktanyilvantartas#15]
community role, legal role, service end change

**Comment by ifjuszalaimihaly** [comment]
Itt pontosan mi a feladat?

**Comment by rrd108** [comment]
nekem úgy tűnik, hogy pár dolog itt hiányzik még
1. a legal role nem változik amikor a community rolet módosítom
2. az utolsó szolgálathoz nem kér be dátumot és nem is állítja be hozzá

**Comment by ifjuszalaimihaly** [comment]
Az 1-es, vagy 2-es community_id-vel rendelkező bhaktáknál megjelenik bal oldalon egy form egy szolgálat vége dátum mezővel. És egy Ed volunteer gombbal. A gomb megnyomása esetén beáll a community_id 4-re, a legalstatusz_id pedig null-ra. A bhakta legutoljára megkezdett szolgálatánál a services táblában megjelenik a beállított dátum a szolgalat_vege mezőben. Beszéljük át, ha más megoldásra gondolnál.

**Comment by rrd108** [comment]
ez így jó lenne de nálam se form se gomb
