### ISSUE TITLE
departments/members dragndrop change

### ISSUE THREAD

**Issue by rrd108** [rrd108/bhaktanyilvantartas#16]
ask for date

**Comment by ifjuszalaimihaly** [comment]
where is this view? In which url?

**Comment by rrd108** [comment]
departments/members a többit szóban 😀

**Comment by ifjuszalaimihaly** [comment]
Ebből még semmi sincs lefejlesztve, ha jól látom. És a felső kategóriákból kell az alsókba húzkódni ugye?

**Comment by rrd108** [comment]
Nem ebből még semmi sincs. 
Bármelyik osztályból bármelyikbe lehet húzni, a sorrend az csak a létszám alapján alakul.

**Comment by ifjuszalaimihaly** [comment]
Egy áthúzással ki is kell vezetni egy embert abból az osztályból, ahonnan kihúztam, vagy csak a másikba kell hozzáadni. Kell-e ellenőrizni, hogy a másiknak tagja-e már?
