### ISSUE TITLE
figyelő eu

### ISSUE THREAD

**Issue by rrd108** [rrd108/bhaktanyilvantartas#4]
Email figyelés havonta lejárás előtti állapotban lévő eu kártyákról

**Comment by ifjuszalaimihaly** [comment]
Létezik már az email funkció?

**Comment by rrd108** [comment]
Ehhez egy cake shell kell amit cronból le lehet futtatni havonta egyszer. Az emailt nekem kellene kiküldeni a névvel meg a eu_card_expiry dátummal. A sanga repoban láthatsz mintákat shellre.

**Comment by ifjuszalaimihaly** [comment]
Kell egy olyan query pluszban, amelyik leszedi a superadminokat, és beteszi az emailcímüket a címlistába?

**Comment by rrd108** [comment]
igen
