### ISSUE TITLE
lekérdezés - nincs eu kártyája

### ISSUE THREAD

**Issue by rrd108** [rrd108/bhaktanyilvantartas#5]

**Comment by ifjuszalaimihaly** [comment]
Melyik view-ban kell megjeleníteni?

**Comment by rrd108** [comment]
én azt csinálnám, hogy a jobb felső sarokban lévő keresőbe be lehessen írni, hogy eu_card_expiry és kapnék egy listát az id-kkel, nevekkel és eu_card_expiry infóval

**Comment by ifjuszalaimihaly** [comment]
Azokat kell listázni, akiknél null az eu card experity?

**Comment by rrd108** [comment]
null vagy lejárt

**Comment by rrd108** [comment]
Úgy néz ki, hogy valamelyik javítást nem mergelted be ide, mert ezt kapom ha rákattintok a kirakott linkre:
Error: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Bhaktas.eu_card_expir' in 'field list'

**Comment by ifjuszalaimihaly** [comment]
It will now work.

**Comment by rrd108** [comment]
kell egy új PR hozzá
