### ISSUE TITLE
notification on 5 years

### ISSUE THREAD

**Issue by rrd108** [rrd108/bhaktanyilvantartas#53]

**Comment by rrd108** [comment]
Check who are those volunteers (communityrole_id == 2) who started their services before a given time.

**Comment by Imran-yousuf** [comment]
Those Bhaktas who has the commutiy role =  önkéntes támogató right?

**Comment by rrd108** [comment]
Yes

**Comment by Imran-yousuf** [comment]
I have pushed the Code. Please review.

**Comment by rrd108** [comment]
please create a pull request

**Comment by Imran-yousuf** [comment]
done.
