### ISSUE TITLE
30-án lehessen látni a következő 1-i állapotot

### ISSUE THREAD

**Issue by rrd108** [rrd108/bhaktanyilvantartas#8]

**Comment by ifjuszalaimihaly** [comment]
Melyik view-ra vonatkozik?

**Comment by rrd108** [comment]
departments/members

rossz az issue neve. tualjdonképpen amit szeretnék, hogy a departments/members nézetben tetszőleges dátumra láthassam az aktuális listát, azaz a departments/members/2017-11-10 azt mutatja ami most van, a departments/members/2017-02-20 meg azt ami február 20-án volt

Mivel a korábbi időpontban lehettek olyan önkéntesek illetve misszionáriusok akik jelenleg nem azok és a communityrole változások dátumát el sem tároljuk szerintem ez nem is lehetséges jelenleg

Mindenesetre ha a jelenleg is misszionárius / önkéntes communityrole-ban lévőket láthatom visszamenőleges (vagy előremenőleges) dátummal az már jó. A probléma másik részére meg létrehoztam ezt: issue #19
